# Generated by Django 2.1.4 on 2018-12-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relurl_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
    ]
