# Generated by Django 2.1.4 on 2018-12-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relurl_app', '0002_remove_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
